version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    networks:
      - monitor
    environment:
      DATABASE_URI: $DATABASE_URI
      STRIIM_API_URL: $STRIIM_API_URL
      API_PORT: $API_PORT
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/pg_hba.conf:/etc/postgresql/14/main/pg_hba.conf
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - monitor

networks:
  monitor:
